Apply automatic changes

diff --git a/config/bin/ghni b/config/bin/ghni
--- a/config/bin/ghni
+++ b/config/bin/ghni
@@ -13,7 +13,7 @@
 set -euo pipefail
 
 usage() {
-  cat << EOF
+	cat <<EOF
 Usage: $(basename "$0") [<issue-url>]
 
 ghni means "GitHub Neovim Issue".
@@ -22,55 +22,55 @@ EOF
 }
 
 if [ "$#" -gt 1 ]; then
-  usage
-  exit 1
+	usage
+	exit 1
 fi
 
-if ! command -v nvr &> /dev/null; then
-  echo "error: 'nvr' is not installed. please install it with 'pip install neovim-remote'" >&2
-  exit 1
+if ! command -v nvr &>/dev/null; then
+	echo "error: 'nvr' is not installed. please install it with 'pip install neovim-remote'" >&2
+	exit 1
 fi
 
 url="${1:-$(pbpaste)}"
 
 if [[ "$url" =~ ^https://github\.com/([^/]+)/([^/]+)/issues/([0-9]+)$ ]]; then
-  owner="${BASH_REMATCH[1]}"
-  reponame="${BASH_REMATCH[2]}"
-  issue_num="${BASH_REMATCH[3]}"
-  repo="${owner}/${reponame}"
+	owner="${BASH_REMATCH[1]}"
+	reponame="${BASH_REMATCH[2]}"
+	issue_num="${BASH_REMATCH[3]}"
+	repo="${owner}/${reponame}"
 else
-  echo "error: invalid issue URL: '$url'" >&2
-  usage
-  exit 1
+	echo "error: invalid issue URL: '$url'" >&2
+	usage
+	exit 1
 fi
 
 session="$repo"
 
 nvim_socket="/tmp/ghni-${owner}-${reponame}.sock"
 
-if ! tmux has-session -t "$session" 2> /dev/null; then
-  tmux new-session -ds "$session"
+if ! tmux has-session -t "$session" 2>/dev/null; then
+	tmux new-session -ds "$session"
 fi
 
 tmux switch-client -t "$session"
 
 # if Neovim is already running
-if nvr --nostart --servername "$nvim_socket" --remote-expr 1 > /dev/null 2>&1; then
-  issue_buf="octo://${owner}/${reponame}/issue/${issue_num}"
+if nvr --nostart --servername "$nvim_socket" --remote-expr 1 >/dev/null 2>&1; then
+	issue_buf="octo://${owner}/${reponame}/issue/${issue_num}"
 
-  found_tab="$(nvr --servername "$nvim_socket" \
-    --remote-expr "bufnr(\"${issue_buf}\")")"
+	found_tab="$(nvr --servername "$nvim_socket" \
+		--remote-expr "bufnr(\"${issue_buf}\")")"
 
-  if [ "$found_tab" -gt 0 ]; then # if tab found, switch to it
-    nvr --servername "$nvim_socket" --remote-send "<cmd>tabnext ${found_tab}<cr>"
-  else # if tab not found, open new tab
-    nvr --servername "$nvim_socket" --remote-send "<cmd>tabnew | Octo ${url}<cr>"
-  fi
+	if [ "$found_tab" -gt 0 ]; then # if tab found, switch to it
+		nvr --servername "$nvim_socket" --remote-send "<cmd>tabnext ${found_tab}<cr>"
+	else # if tab not found, open new tab
+		nvr --servername "$nvim_socket" --remote-send "<cmd>tabnew | Octo ${url}<cr>"
+	fi
 
-  tmux last-window
+	tmux last-window
 
 # if Neovim is not running
 else
-  tmux new-window -t "$session" -n "ghni-issue-${issue_num}" \
-    "NVIM_LISTEN_ADDRESS=${nvim_socket} nvim -c 'Octo ${url}'"
+	tmux new-window -t "$session" -n "ghni-issue-${issue_num}" \
+		"NVIM_LISTEN_ADDRESS=${nvim_socket} nvim -c 'Octo ${url}'"
 fi
diff --git a/config/bin/lngo b/config/bin/lngo
--- a/config/bin/lngo
+++ b/config/bin/lngo
@@ -7,13 +7,13 @@ dir=$(git root)
 
 repo=${dir#${GHQPATH}/}
 if [ -z "$repo" ]; then
-  echo "Could not detect the repository name. Please execute in a local repository on $(ghq root)."
-  exit 1
+	echo "Could not detect the repository name. Please execute in a local repository on $(ghq root)."
+	exit 1
 fi
 
 if [ -z "$(find . -type f -name '*.go')" ]; then
-  echo "Not found go files in the working directory."
-  exit 1
+	echo "Not found go files in the working directory."
+	exit 1
 fi
 
 ln -snv "$(pwd)" "$GOPATH/src/$repo"
diff --git a/config/bin/renovate-dryrun b/config/bin/renovate-dryrun
--- a/config/bin/renovate-dryrun
+++ b/config/bin/renovate-dryrun
@@ -31,7 +31,7 @@ set -euo pipefail
 #   packageFile: terraform/tailscale/main.tf
 
 usage() {
-  cat << EOF
+	cat <<EOF
 Usage: $0 [options]
 
 Options:
@@ -40,30 +40,30 @@ Options:
   -b, --branch <branch>       Branch to dry-run the Renovate (default: current branch)
   --raw                       Show the raw Renovate log
 EOF
-  exit 1
+	exit 1
 }
 
 while (($#)); do
-  case "$1" in
-    -h | --help) usage ;;
-    -c | --config)
-      config_file="$2"
-      shift 2
-      ;;
-    -b | --branch)
-      branch="$2"
-      shift 2
-      ;;
-    --raw)
-      raw=true
-      shift
-      ;;
-    -*)
-      echo "Unknown option: $1" >&2
-      usage
-      ;;
-    *) break ;;
-  esac
+	case "$1" in
+	-h | --help) usage ;;
+	-c | --config)
+		config_file="$2"
+		shift 2
+		;;
+	-b | --branch)
+		branch="$2"
+		shift 2
+		;;
+	--raw)
+		raw=true
+		shift
+		;;
+	-*)
+		echo "Unknown option: $1" >&2
+		usage
+		;;
+	*) break ;;
+	esac
 done
 
 raw="${raw:-false}"
@@ -77,41 +77,41 @@ repo_name="$(basename "$(dirname "$root_path")")/$(basename "$root_path")"
 gh_token="$(gh-token)"
 
 dryrun() {
-  env LOG_LEVEL=debug \
-    RENOVATE_CONFIG_FILE="$config_file" \
-    RENOVATE_BASE_BRANCHES="$branch" \
-    npx -y renovate \
-    --token="$gh_token" \
-    --schedule="" \
-    --require-config=ignored \
-    --dry-run=full \
-    "$repo_name"
+	env LOG_LEVEL=debug \
+		RENOVATE_CONFIG_FILE="$config_file" \
+		RENOVATE_BASE_BRANCHES="$branch" \
+		npx -y renovate \
+		--token="$gh_token" \
+		--schedule="" \
+		--require-config=ignored \
+		--dry-run=full \
+		"$repo_name"
 }
 
 if [[ "$raw" == "true" ]]; then
-  dryrun
-  exit
+	dryrun
+	exit
 fi
 
 renovate_log="$(dryrun)"
 
 find_json() {
-  target_log="$1"
+	target_log="$1"
 
-  printf '{'
-  echo "$renovate_log" | perl -ne 'BEGIN { $target_log = shift } print if /$target_log/ .. !/$target_log/ && /^\s*[A-Z]+:/' "$target_log" | sed '1d;$d' | sed -e 's/: undefined/: null/'
-  printf '}\n'
+	printf '{'
+	echo "$renovate_log" | perl -ne 'BEGIN { $target_log = shift } print if /$target_log/ .. !/$target_log/ && /^\s*[A-Z]+:/' "$target_log" | sed '1d;$d' | sed -e 's/: undefined/: null/'
+	printf '}\n'
 }
 
 parse_log() {
-  branch_summary="$(find_json 'DEBUG: Branch summary' | jq -r '.branches | map({ key: .branchName, value: .}) | from_entries')"
-  branches_information="$(find_json 'DEBUG: branches info extended' | jq -r '.branchesInformation | map({ key: .branchName, value: .}) | from_entries')"
+	branch_summary="$(find_json 'DEBUG: Branch summary' | jq -r '.branches | map({ key: .branchName, value: .}) | from_entries')"
+	branches_information="$(find_json 'DEBUG: branches info extended' | jq -r '.branchesInformation | map({ key: .branchName, value: .}) | from_entries')"
 
-  jq -rn \
-    --argjson branch_summary "$branch_summary" \
-    --argjson branches_information "$branches_information" \
-    "$(
-      cat << 'JQ'
+	jq -rn \
+		--argjson branch_summary "$branch_summary" \
+		--argjson branches_information "$branches_information" \
+		"$(
+			cat <<'JQ'
 $branch_summary | map({ key: .branchName, value: .}) | from_entries as $summary |
 $branches_information | map({ key: .branchName, value: .}) | from_entries as $info |
 $info | with_entries(.value += $summary[.key]) | map(
@@ -124,20 +124,20 @@ $info | with_entries(.value += $summary[.key]) | map(
   ) | join("\n"))
 ) | join("\n")
 JQ
-    )"
+		)"
 
-  echo "## Detected dependencies (no upgrades)"
-  echo
+	echo "## Detected dependencies (no upgrades)"
+	echo
 
-  package_files="$(find_json 'DEBUG: Checking packageFiles for deprecated packages' | jq -r .packageFiles)"
-  if [[ "$(jq -r 'length' <<< "$package_files")" == 0 ]]; then
-    package_files="$(find_json 'DEBUG: packageFiles with updates' | jq -r .config)"
-  fi
+	package_files="$(find_json 'DEBUG: Checking packageFiles for deprecated packages' | jq -r .packageFiles)"
+	if [[ "$(jq -r 'length' <<<"$package_files")" == 0 ]]; then
+		package_files="$(find_json 'DEBUG: packageFiles with updates' | jq -r .config)"
+	fi
 
-  jq -rn \
-    --argjson package_files "$package_files" \
-    "$(
-      cat << 'JQ'
+	jq -rn \
+		--argjson package_files "$package_files" \
+		"$(
+			cat <<'JQ'
 $package_files | to_entries | map(
   "\(.key)\n" + (.value | map(
     "  \(.packageFile)\n" +
@@ -148,13 +148,13 @@ $package_files | to_entries | map(
   ) | join("\n\n"))
 ) | join("\n\n")
 JQ
-    )"
+		)"
 }
 
 parse_log || {
-  echo "[error] Failed to parse the Renovate log" >&2
-  tmp_log="$(mktemp -t renovate-dryrun.XXXXXX.log)"
-  echo "$renovate_log" > "$tmp_log"
-  echo "full log: $tmp_log" >&2
-  exit 1
+	echo "[error] Failed to parse the Renovate log" >&2
+	tmp_log="$(mktemp -t renovate-dryrun.XXXXXX.log)"
+	echo "$renovate_log" >"$tmp_log"
+	echo "full log: $tmp_log" >&2
+	exit 1
 }
diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -5,7 +5,7 @@ cd "$(dirname "$0")/.."
 source scripts/utils.bash
 
 usage() {
-  cat << EOS
+	cat <<EOS
 USAGE: $0 [options...]
 
 OPTIONS
@@ -18,103 +18,103 @@ EOS
 }
 
 log-exec() {
-  if is_dryrun; then
-    printf '[dryrun] '
-  else
-    printf '[run] '
-  fi
-  echo "$@"
+	if is_dryrun; then
+		printf '[dryrun] '
+	else
+		printf '[run] '
+	fi
+	echo "$@"
 
-  if ! is_dryrun; then
-    "$@"
-  fi
+	if ! is_dryrun; then
+		"$@"
+	fi
 }
 
 is_dryrun() {
-  test -n "$DRYRUN"
+	test -n "$DRYRUN"
 }
 
 is_force() {
-  test -n "$FORCE"
+	test -n "$FORCE"
 }
 
 while [ $# -gt 0 ]; do
-  case "$1" in
-    --help | -h)
-      usage
-      exit
-      ;;
+	case "$1" in
+	--help | -h)
+		usage
+		exit
+		;;
 
-    --debug | -d)
-      set -x
-      shift
-      ;;
+	--debug | -d)
+		set -x
+		shift
+		;;
 
-    --dry-run | -n)
-      DRYRUN=1
-      shift
-      ;;
+	--dry-run | -n)
+		DRYRUN=1
+		shift
+		;;
 
-    --force | -f)
-      FORCE=1
-      shift
-      ;;
+	--force | -f)
+		FORCE=1
+		shift
+		;;
 
-    --tags | -t)
-      tags="$(tr ',' '\n' <<< "$2")"
-      shift 2
-      ;;
+	--tags | -t)
+		tags="$(tr ',' '\n' <<<"$2")"
+		shift 2
+		;;
 
-    -*)
-      echo "[ERROR] Invalid option '$1'"
-      usage
-      exit 1
-      ;;
-  esac
+	-*)
+		echo "[ERROR] Invalid option '$1'"
+		usage
+		exit 1
+		;;
+	esac
 done
 
 function is_absolute_path {
-  if [[ $1 == /* ]]; then
-    echo "true"
-  else
-    echo "false"
-  fi
+	if [[ $1 == /* ]]; then
+		echo "true"
+	else
+		echo "false"
+	fi
 }
 
 # define a symbolink link
 # usage: sym <src> <dest>
 sym() {
-  src="$1"
-  if [[ "$src" != /* ]]; then
-    src="$PWD/$src"
-  fi
+	src="$1"
+	if [[ "$src" != /* ]]; then
+		src="$PWD/$src"
+	fi
 
-  dst="$2"
-  dst_dir="$(dirname "$dst")"
+	dst="$2"
+	dst_dir="$(dirname "$dst")"
 
-  if [ ! -d "$dst_dir" ]; then
-    log-exec mkdir -p "$dst_dir"
-  fi
+	if [ ! -d "$dst_dir" ]; then
+		log-exec mkdir -p "$dst_dir"
+	fi
 
-  if is_force || [ ! -e "$dst" ]; then
-    if [ -d "$dst" ]; then
-      log-exec rm -r "$dst"
-    fi
-    log-exec ln -sfnv "$src" "$dst"
-  fi
+	if is_force || [ ! -e "$dst" ]; then
+		if [ -d "$dst" ]; then
+			log-exec rm -r "$dst"
+		fi
+		log-exec ln -sfnv "$src" "$dst"
+	fi
 }
 
 # check tag matching
 # usage: match_tag <tag>
 match_tag() {
-  tag="$1"
+	tag="$1"
 
-  # if the --tags option is not set, all tags are assumed to be specified
-  if [ -z "${tags:-}" ]; then
-    return 0
-  fi
+	# if the --tags option is not set, all tags are assumed to be specified
+	if [ -z "${tags:-}" ]; then
+		return 0
+	fi
 
-  grep -q -F "$tag" <<< "$tags"
+	grep -q -F "$tag" <<<"$tags"
 }
 
 source symlinks
