bin/renovate-dryrun: output the log when errors occur

diff --git a/config/bin/renovate-dryrun b/config/bin/renovate-dryrun
--- a/config/bin/renovate-dryrun
+++ b/config/bin/renovate-dryrun
@@ -75,4 +75,10 @@ $summary | with_entries(.value += $info[.key]) | map(
   ) | join("\n"))
 ) | join("\n")
 JQ
-  )"
+  )" || {
+  echo "[error] Failed to parse the Renovate log" >&2
+  tmp_log="$(mktemp -t renovate-dryrun.XXXXXX.log)"
+  echo "$renovate_log" > "$tmp_log"
+  echo "full log: $tmp_log" >&2
+  exit 1
+}
